### ISSUE TITLE
extend UI with code editor

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/aydo#1]
http://127.0.0.1:8080/web/client/files

extend the web ui:

embed code editor so we can edit

- golang files
- yaml
- vlang
- markdown

with syntax coloring

**Comment by xmonader** [comment]
There is a code editor ( ttps://github.com/despiegk/sftpgo/blob/main/templates/webclient/editfile.html#L126 ) in the editfile template using codemirror, but the syntax highlighting isn't working properly

![image](https://user-images.githubusercontent.com/64129/236154151-677f2391-b3ba-49fd-b41e-cb318427f942.png)

**Comment by alichaddad** [comment]
Syntax highlighting is fixed in my [fork](https://github.com/alichaddad/sftpgo/tree/dev).

**Comment by despiegk** [comment]
fantastic

**Comment by alichaddad** [comment]
Vlang is now supported

**Comment by despiegk** [comment]
how to use it?

**Comment by xmonader** [comment]
it's runs out of the box when you try to edit a file

**Comment by despiegk** [comment]
which branch?

**Comment by alichaddad** [comment]
Code is merged on development now for both web3 proxy and aydo repos

**Comment by mohamedamer453** [comment]
Verified.

Code editor for the mentioned languages was added and it also supports syntax highlighting.

[Screencast from 01-06-23 14:43:07.webm](https://github.com/freeflowuniverse/aydo/assets/101194226/018efe13-4bbf-4211-a4a5-86033c465b2f)

**Comment by despiegk** [comment]
super cool, i'll try tomorrow
