### ISSUE TITLE
see if we can integrate sftpgo in web3 proxy

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/aydo#5]
see if we can compile and load it in web3 proxy

maybe an option defines if we load it or not and what the admin username is

**Comment by alichaddad** [comment]
Can we have more elaboration on the requirements?
- Which `sftpgo` functionalities should be  exposed via the client?
- Do we need to integrate the `sftpgo` server itself in the proxy as well?
- Give example use cases for a better understanding of the integration

cc @xmonader

**Comment by xmonader** [comment]
I believe @despiegk meant to be able to launch server as a subcommand of the proxy or the functionality to be exposed as a module on the proxy

**Comment by despiegk** [comment]
the code needs to be in the golang binary, so we only have one

**Comment by alichaddad** [comment]
There is no way to integrate the server into web3 due to the fact that the server logic in `sftpgo` not being exposed. The alternative is to integrate the code ourselves but this will mean extra overhead for development and maintenance in the future in case we want to have the latest upstream updates

**Comment by alichaddad** [comment]
Integration mostly done, just needs to consider how to deliver the necessary static failed needed by sftpgo to the web proxy deployment

**Comment by despiegk** [comment]
please define what we will have now?

**Comment by alichaddad** [comment]
Sftpgo can be run using web3 proxy by following this doc: https://github.com/threefoldtech/web3_proxy/blob/development_sftpgo/manual/src/server/sftpgo.md

**Comment by mohamedamer453** [comment]
Verified.

I was able to follow the docs and run sftp go through the webproxy using both methods mentioned in https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md 

- First method is by running [docker compose](https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md#using-docker-compose) (recommended method )
   This method is very easy and simple all you have to do is run one command in the root directory of the webproxy and you're good to go.

- Second method  is by[ manually configuring the instance](https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md#enabling-the-server) through `sftpgo.json` file and the required env vars.
   This method is a bit more complicated and has more steps, but the flow is documented well.

and it works fine with both methods and all the defined functionalities are working without any issues.

![image](https://github.com/freeflowuniverse/aydo/assets/101194226/e755f9af-738f-44b4-a312-ca1a32c48979)
