### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/aydo#7]
- see how to extend with reverse proxy basic functionality
- e/g/ https://3botip/dao goes to http://localhost:8888 
- the localhost would be our V backend
- sftpgo uses letsencrypt already, so https to http should be easy
- the 3botip is the pub ip address using letsencrypt
- see if we can add API for this so we can configure it from VLANG

**Comment by despiegk** [comment]
this allows sftpo to be the default front end for all our functionality

**Comment by xmonader** [comment]
even with a public ip, you need the domain to be resolvable by let's encrypt, otherwise it won't be able to do dns01 or http01 to verify the ownership of a domain to issue a certificate

**Comment by despiegk** [comment]
is not a prob, pub ip addr ok for now

**Comment by alichaddad** [comment]
I am not entirely sure what is needed here.
Is the goal to make use of sftpgo server to expose the web3 proxy API?
What is the API that we can add and to configure what?

**Comment by alichaddad** [comment]
I am going to add a new endpoint in sftpgo: /dao that routes to a configurable server as a start until more details are gathered

**Comment by despiegk** [comment]
we are ok, we can cancel this one, we can work around it using our web2gateway, ok to close
