### ISSUE TITLE
good enough docu

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/aydo#9]
can be small but need to know

- how to build
- how to get started
- how to use the new functionality

**Comment by alichaddad** [comment]
Can be used on branch: `development_sftpgo` in web3 proxy

Please check the [docs](https://github.com/threefoldtech/web3_proxy/blob/development_sftpgo/manual/src/server/sftpgo.md) to get the setup and running

**Comment by despiegk** [comment]
link doesn't work

**Comment by alichaddad** [comment]
Branch was merged to devevlopment, can be found [here](https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md) now

**Comment by mohamedamer453** [comment]
Verified.

The docs are very simple and clear, and the user can choose one of 2 methods for running sftpgo, and both methods are documented well and easy to follow. and if the user follows the [recommended](https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md#using-docker-compose) method then everything can be up and running just by executing `docker-compose up -d` in the root directory.

https://github.com/threefoldtech/web3_proxy/blob/development/manual/src/server/sftpgo.md
